### ISSUE TITLE
4 fold repetition in match games

### ISSUE THREAD

**Issue by Dorus** [glinscott/leela-chess#232] opened 2018-04-03 08:06 UTC
http://lczero.org/match_game/37626 move 45-51 has the same 2 positions 4 times.

From the forums btw: https://groups.google.com/forum/#!topic/lczero/nGTLSoA5Vg8

**Comment by mooskagh** [comment] 2018-04-05 10:25
Discussed today in discord.
Depending on how NNCache is implemented, that may be caused by using cached version of NN output, even if repetition count for previous nodes are different.

Also the fact that game controller (client.exe) didn't detect that and not stopped the game is a separate issue.

**Comment by Dorus** [comment] 2018-04-05 10:26
It seems wrong to use NNCache when history is different. Shouldn't the NNCache be based on the entire NN input?

**Comment by Tilps** [comment] 2018-04-05 11:01
There seems to be a bit of an odd missmatch in the UCTSearch code.  play_simulation refuses to create children if it considers the current position as a draw, but think forces expansion of the root node without checking for draw status.

**Comment by mooskagh** [comment] 2018-04-05 11:05
What would you expect it to do?
It's a drawn position, but it's still asked to play the move. It has to
pick a move to play.

It's possible that both sides thought that draw is the best they can aim
for, and did threefold repetition on purpose (and controlled didn't detect
it), but it's very improbable given material difference.

**Comment by Tilps** [comment] 2018-04-05 12:26
Well yeah there is a further much more important missmatch which is that the match game harness code implements 5 rep auto draw, with 3 rep requiring draw proposal, but the uci protocol doesn't officially support draw proposals. (I was not aware uci protocol was quite so limited...)
But I wonder how confusing it is to the training that the engine force evaluates as 0.5 at 3 repetitions, but the actual outcome of the game could be non-draw because the game isn't actually evaluated as a draw until 5 repetitions, and with temperature 1 it could easily break out and go on to a non-draw position.
Although I wonder if its even worse for the 50 move limit, since the client harness implements a 75 move limit without draw offers, and so for the next 25 moves the engine is going to report 'everything' as drawn ignoring the neural net, but maybe a checkmate happens in those in those moves.
Technically the client harness is implementing real rules, but I guess we should fork it?

**Comment by Tilps** [comment] 2018-04-05 12:49
Ahh nevermind, the training isn't run through the harness.

**Comment by killerducky** [comment] 2018-04-11 19:14
Fixed in #275.

**Closed by killerducky** 2018-04-11 19:14 UTC
