### ISSUE TITLE
Allow to set thread limit for lczero on client.exe to speed up calculation

### ISSUE THREAD

**Issue by ChameleonRed** [glinscott/leela-chess#458] opened 2018-04-28 19:44 UTC
It will be nice to use more cores if it helps to calculate faster.

**Comment by jjoshua2** [comment] 2018-04-28 20:59
Instead what we need is a command to run multiple clients since each one
only used 1 thread on purpose

**Comment by killerducky** [comment] 2018-04-29 19:56
Duplicate of #344

**Closed by killerducky** 2018-04-29 19:56 UTC
