### ISSUE TITLE
black pawns refusing to promote/underpromoting 

### ISSUE THREAD

**Issue by ppapasaikas** [glinscott/leela-chess#349] opened 2018-04-18 00:26 UTC
There have been multiple reports of a black specific issue where plack pawns do not take a promotion or underpromote sometimes drawing winning positions.
See e.g
http://lczero.org/match_game/98272
http://lczero.org/match_game/99187
https://lichess.org/L9UsfeNB#155

Issue appears both in self-training and actual games.
Seems related to #236, #231

Also possibly (???) related issue: As black not recognizing 3-fold repetition again drawing a winning position.
see e.g:
 http://lczero.org/match_game/98422

**Comment by smk-kent** [comment] 2018-04-18 01:51
Various match games where this was an issue: 98422, 98277, 98272, 98123, 98496. Notice that the [lichess game](https://lichess.org/study/kLXrkT4M) against IM lovlas with the failed Lucena conversion may also be caused by this, perhaps indirectly. Of those games, [98123](http://lczero.org/match_game/98123) is not about promotion, just the 3-fold issue: black failed to win a QvR endgame, not by the 50moves rule, but by 3-fold. In all those games, black was missing out.

**Comment by smk-kent** [comment] 2018-04-18 02:02
also: http://lczero.org/match_game/98541 the KBNvK endgame, drawn by 3-fold (not 50 moves), again black missing out

**Comment by patrickchess** [comment] 2018-04-18 02:07
I wonder if the bug is related to the low draw rate (and the apparently weak endgame play observed in TCEC matches). In this Google Groups post it was conjectured that the temperature was responsible, but this seems more likely.

https://groups.google.com/forum/#!topic/lczero/dU8v637v2Ig

**Comment by patrickchess** [comment] 2018-04-18 02:34
@smk-kent Training games use the Stockfish repetition draw code, which uses the 3-fold rule, IIRC. The 5-fold draw rule was -- again IIRC -- only an issue in match games and was since fixed. 

Reference: https://github.com/glinscott/leela-chess/pull/275

**Comment by smk-kent** [comment] 2018-04-18 02:40
I was told - on the discord chat (by MTGO) - that it was/is used in training games. Whatever it is, it looks as if the counting is not done correctly for black, because I have not found games where white was affected but plenty of games affecting black.

**Comment by patrickchess** [comment] 2018-04-18 02:54
@smk-kent I just talked to Gary on discord. He's certain that both training and match use 3-fold now (and that training always has).

We discovered that the 50-move rule is being incorrectly implemented as a 25-move draw rule in match games, which caused the behavior in http://lczero.org/match_game/98541. (Note it's not actually a threefold!) This is an issue separate from the promotion, since it stems from the code used to conduct match games.

**Comment by smk-kent** [comment] 2018-04-18 03:12
that also explains [98123](http://lczero.org/match_game/98123), again 25 moves. At least it does not mess up the net, only distorts match results.

**Comment by smk-kent** [comment] 2018-04-18 04:04
I was told the problem was that black would not see a promotion (other than knight). But in 4 of the games above, 98422, 98543, 98579 and 99187 black could have won anyway, even with knight or no promotions.

**Comment by patrickchess** [comment] 2018-04-18 04:11
@smk-kent I checked a few of the games you posted (but not all). It seems that Leela was planning on winning those but got stopped by the 25-move bug. The network does not penalize inefficient wins, so it's no surprise it was taking its time.

**Comment by killerducky** [comment] 2018-04-18 05:53
This will be fixed by #351.

**Closed** 2018-04-18 18:00 UTC
